"""update db

Revision ID: ca53735d3595
Revises: fc72eaaaa06b
Create Date: 2026-01-07 19:18:36.161139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca53735d3595'
down_revision: Union[str, Sequence[str], None] = 'fc72eaaaa06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrepreneurs', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entrepreneurs', 'created_at')
    # ### end Alembic commands ###
